### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by LexLinux** [snakedye/sway_config#3]
Hello, thank you for hosting the dotfiles on github!
I've followed the steps in the README and everything is working minus the beautiful icons in the screenshot, are the Material Icons referring to Googles Material Design Icons ?

**Comment by MGThePro** [comment]
I'm having the same issue

**Comment by MGThePro** [comment]
I changed the icon theme in the waybar config line 181,210 and 262, uncommented those lines that were commented, and not it's fixed. After changing it, it took a while (and reloading the config multiple times) to finally work properly, so idk if that was what fixed it

**Comment by LexLinux** [comment]
> I changed the icon theme in the waybar config line 181,210 and 262, uncommented those lines that were commented, and not it's fixed. After changing it, it took a while (and reloading the config multiple times) to finally work properly, so idk if that was what fixed it

Thank you for the reply, I will give it and try just now

**Comment by snakedye** [comment]
It's fixed, I've added the icons to nwgbar in the nwg-launchers directory. It should now work.

**Comment by snakedye** [comment]
> Hello, thank you for hosting the dotfiles on github!
> I've followed the steps in the README and everything is working minus the beautiful icons in the screenshot, are the Material Icons referring to Googles Material Design Icons ?

Yes Google Material Icons. You know what, I'll just add my fonts to the repo.

**Comment by LexLinux** [comment]
@snakedye I managed to get it sorted out, i purchased the Material Icons Pro font :) and pull down the git again ... all is now woring thanks for the help!
