### ISSUE TITLE
Glyphs on elements with text are smaller than text

### ISSUE THREAD

**Issue by Neules** [snakedye/sway_config#4]
Icons appear smaller than the base `font-size` for text, but I cannot increase it by using `font-size` at any `#id` (#waybar, #workspaces, etc) if using a font for text and another for glyphs, i.e. `Fira sans` for text and a nerd font for glyphs (there's no nerd patch for `Fira sans` I guess). I have to use the same font for text and glyphs to get what I want.

Does anybody know how to overcome this situation?

**Comment by snakedye** [comment]
Change your icons font-size in * { and your text in #waybar. If the icons are tiny removing font-size in * { also does the job.

**Comment by Neules** [comment]
Woh sorry I didn't express myself, it's not working on an element with text + icon. I should change issue's title. My bad.
I'm trying to increase the icon on elements like `pulseaudio` or `network` where there's text and icon, which I cannot because text is `Fira sans` and the icons cannot be `Nerd Fira sans` because it doesn't exist.

On the screenshot I increased text font size on #pulseaudio but not the icon size, but on #disk or #temperature the icon has a proper size but the text is a nerd font different from `Fira sans`.

![scrot](https://user-images.githubusercontent.com/34288954/93942458-ba0ea180-fd30-11ea-988f-b72abeb12889.png)

**Comment by snakedye** [comment]
Sorry for the delay. Have you tried to remove font-size from * and window#waybar?

**Comment by Neules** [comment]
Yup. No luck.

**Comment by snakedye** [comment]
What happens when you increase the size of the bar?
