### ISSUE TITLE
Font not found

### ISSUE THREAD

**Issue by dR3b** [snakedye/sway_config#6]
I have found this error:

https://github.com/snakedye/sway_config/blob/00472430f08a5ffc5ba218bbb5c2f4c53ff95475/install.sh#L67

```
~ » trizen -S ttf-nerd-fonts
:: ttf-nerd-fonts not found.
```

**Comment by snakedye** [comment]
remove the -S or try with ttf-nerd-fonts-symbols.

I use ttf-nerd-fonts on paru and yay and they both work.

**Comment by dR3b** [comment]
Trizen, Paru and Yay are all frontends for pacman. There is no package called: ttf-nerd-fonts

**Comment by snakedye** [comment]
This has been [fixed](https://github.com/snakedye/sway_config/blob/master/install.sh)
